const config = {
  coverageDirectory: 'coverage',
  testEnvironment: 'jsdom',
  roots: ['components'],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  testMatch: ['<rootDir>/components/**/__tests__/**/*.{js,jsx,ts,tsx}'],
  transformIgnorePatterns: ['<rootDir>/lib/', '<rootDir>/es/', '<rootDir>/docs/'],
  collectCoverageFrom: [
    'components/**/*.{ts,tsx}',
    '!components/index.ts',
    '!components/**/style.ts',
    '!components/**/styles.ts',
    '!components/**/type.ts',
    '!components/**/posi.ts',
    '!components/prism/**',
    '!components/code/**',
    '!components/md/**',
    '!components/md-style/**',
    '!components/katex/**',
    '!components/@moneko/**',
    '!components/@introduce/**',
    '!components/notification/index.tsx',
    '!components/qrcode/qrcode.ts',
    '!components/qrcode/index.tsx',
    '!components/color-palette/index.tsx',
    '!components/img/index.tsx',
    '!components/input/index.tsx',
    '!components/menu/index.tsx',
    '!components/tree/index.tsx',
    '!components/tabs/index.tsx',
    '!components/select/index.tsx',
    '!components/pagination/index.tsx',
    '!components/popover/index.tsx',
    '!components/provider/index.tsx',
    '!components/highlight-text/index.tsx',
    '!components/checkbox/index.tsx',
    '!components/cron/index.tsx',
    '!components/date-picker/index.tsx',
    '!components/date-picker/panel.tsx',
    '!components/modal/index.tsx',
    '!components/modal/hooks.tsx',
    '!components/capture-screen/index.tsx',
    '!components/dropdown/index.tsx',
    '!components/back-top/index.tsx',
    '!components/avatar/index.tsx',
    '!components/avatar/group.tsx',
    '!components/cron/year.tsx',
    '!components/marquee/index.tsx',
    '!components/carousel/index.tsx',
    '!components/from-schema/index.ts',
    '!components/get-options/index.ts',
    '!components/icon/index.ts',
    '!components/img/lazy.tsx',
    '!components/input-number/index.tsx',
    '!components/segmented/index.tsx',
    '!components/spin/index.tsx',
    '!components/switch/index.tsx',
    '!components/table/index.tsx',
    '!components/tag/index.tsx',
    '!components/theme/index.ts',
    '!components/button/index.tsx',
    '!components/collapse/index.tsx',
    '!components/color-picker/index.tsx',
    '!components/cron/hour.tsx',
    '!components/cron/minute.tsx',
    '!components/glass-panel/index.tsx',
    '!components/radio/index.tsx',
    '!components/skeleton/index.tsx',
    '!components/**/__tests__/**',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/test/',
    '<rootDir>/lib/',
    '<rootDir>/es/',
    '<rootDir>/docs/',
    '<rootDir>/node_modules/',
  ],
  testPathIgnorePatterns: [
    '/prism\\.js$',
    '/components/code/',
    '/components/md/',
    '<rootDir>/test/',
    '<rootDir>/lib/',
    '<rootDir>/es/',
    '<rootDir>/docs/',
    '<rootDir>/node_modules/',
  ],
  setupFilesAfterEnv: [
    '<rootDir>/test/setup.ts',
    '<rootDir>/test/css-highlights.ts',
    '<rootDir>/test/canvas.ts',
    '<rootDir>/test/event.ts',
    '<rootDir>/test/structured-clone.ts',
    '<rootDir>/test/install.ts',
  ],
  moduleNameMapper: {
    'neko-ui': '<rootDir>/components/index.ts',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/test/file.mock.ts',
    '\\.(css|less)$': '<rootDir>/test/obj-proxy.ts',
    '\\?raw$': '<rootDir>/test/file.mock.ts',
    '\\?url$': '<rootDir>/test/file.mock.ts',
  },
  transform: {
    '^.+\\.[jt]sx?$': '<rootDir>/test/transform-solid.mjs',
  },
};

export default config;
