const config = {
  coverageDirectory: 'coverage',
  testEnvironment: 'jsdom',
  roots: ['components'],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  testMatch: ['<rootDir>/components/**/__tests__/**/*.{js,jsx,ts,tsx}'],
  transformIgnorePatterns: ['<rootDir>/lib/', '<rootDir>/es/', '<rootDir>/docs/'],
  collectCoverageFrom: [
    'components/**/*.{ts,tsx}',
    '!components/index.ts',
    '!components/**/style.ts',
    '!components/**/styles.ts',
    '!components/**/type.ts',
    '!components/**/posi.ts',
    '!components/prism/**',
    '!components/code/**',
    '!components/md/**',
    '!components/md-style/**',
    '!components/katex/**',
    '!components/@moneko/**',
    '!components/@introduce/**',
    '!components/notification/index.tsx',
    '!components/qrcode/qrcode.ts',
    '!components/qrcode/index.tsx',
    '!components/color-palette/index.tsx',
    '!components/img/index.tsx',
    '!components/input/index.tsx',
    '!components/menu/index.tsx',
    '!components/tree/index.tsx',
    '!components/tabs/index.tsx',
    '!components/select/index.tsx',
    '!components/pagination/index.tsx',
    '!components/popover/index.tsx',
    '!components/provider/index.tsx',
    '!components/highlight-text/index.tsx',
    '!components/checkbox/index.tsx',
    '!components/cron/index.tsx',
    '!components/date-picker/index.tsx',
    '!components/modal/index.tsx',
    '!components/**/__tests__/**',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/test/',
    '<rootDir>/lib/',
    '<rootDir>/es/',
    '<rootDir>/docs/',
    '<rootDir>/node_modules/',
  ],
  testPathIgnorePatterns: [
    '/prism\\.js$',
    '/components/code/',
    '/components/md/',
    '<rootDir>/test/',
    '<rootDir>/lib/',
    '<rootDir>/es/',
    '<rootDir>/docs/',
    '<rootDir>/node_modules/',
  ],
  setupFilesAfterEnv: [
    '<rootDir>/test/setup.ts',
    '<rootDir>/test/css-highlights.ts',
    '<rootDir>/test/canvas.ts',
    '<rootDir>/test/event.ts',
    '<rootDir>/test/structured-clone.ts',
    '<rootDir>/test/install.ts',
  ],
  moduleNameMapper: {
    'neko-ui': '<rootDir>/components/index.ts',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/test/file.mock.ts',
    '\\.(css|less)$': '<rootDir>/test/obj-proxy.ts',
    '\\?raw$': '<rootDir>/test/file.mock.ts',
    '\\?url$': '<rootDir>/test/file.mock.ts',
  },
  transform: {
    '^.+\\.[jt]sx?$': [
      'babel-jest',
      {
        presets: [
          ['@babel/preset-env', { targets: { node: 'current' } }],
          '@babel/preset-typescript',
          ['babel-preset-solid', { generate: 'dom', hydratable: false }],
        ],
      },
    ],
  },
};

export default config;
